@country_background {
  :China => "https://upload.wikimedia.org/wikipedia/commons/c/c4/Sample_PRC_Flag.svg",
  :India => "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/320px-Flag_of_India.svg.png",
  "United States of America" => "http://p1.pichost.me/i/25/1479130.jpg",
  :Indonesia => "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/2000px-Flag_of_Indonesia.svg.png",
  :Brazil => "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png",
  :Pakistan => "http://wallvan.com/wp-content/uploads/2014/03/Pakistan-Flag-Wallpaper.jpg",
  :Nigeria => "http://www.outinperth.com/wp-content/uploads/2012/11/Nigeria-Flag.jpg",
  :Bangladesh => "http://www.worldatlas.com/webimage/flags/countrys/zzzflags/bdlarge.gif",
  :Russia => "https://upload.wikimedia.org/wikipedia/en/archive/f/f3/20120812153730!Flag_of_Russia.svg",
  :Japan => "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/1280px-Flag_of_Japan.svg.png",
  :Mexico => "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Mexico_(reverse).png",
  :Philippines => "https://flagspot.net/images/p/ph.gif",
  :Vietnam => "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
  :Ethiopia => "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/2000px-Flag_of_Ethiopia.svg.png",
  :Egypt => "http://egyptflag.facts.co/egyptflagof/EgyptFlagImage1.png",
  :Germany => "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/1280px-Flag_of_Germany.svg.png",
  :Iran => "http://www.mapsofworld.com/images/world-countries-flags/iran-flag.gif",
  :Turkey => "http://www.worldatlas.com/webimage/flags/countrys/zzzflags/trlarge.gif",
  "Democratic Republic of the Congo" => "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/1280px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png",
  :France => "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Civil_and_Naval_Ensign_of_France.svg/2000px-Civil_and_Naval_Ensign_of_France.svg.png",
  :Thailand => "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/2000px-Flag_of_Thailand.svg.png",
  "United Kingdom" => "https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/1280px-Flag_of_the_United_Kingdom.svg.png",
  :Italy => "http://italianflag.facts.co/italyflag/ItalyFlagImage1.png",
  "South Africa" => "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/1280px-Flag_of_South_Africa.svg.png",
  :Myanmar => "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/2000px-Flag_of_Myanmar.svg.png",
  "South Korea" => "http://flagpedia.net/data/flags/ultra/kr.png"
  :Colombia => "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/2000px-Flag_of_Colombia.svg.png",
  :Tanzania => "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/1280px-Flag_of_Tanzania.svg.png",
  :Kenya => "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/2000px-Flag_of_Kenya.svg.png",
  :Spain => "http://www.spain-flag.eu/photos/spain-flag.gif",
  :Argentina => "http://www.onlinestores.com/flagdetective/images/download/argentina-hi.jpg",
  :Ukraine => "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/2000px-Flag_of_Ukraine.svg.png",
  :Algeria => "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg",
  :Poland => "http://www.worldatlas.com/webimage/flags/countrys/zzzflags/pllarge.gif",
  :
  }